import type { Metadata } from 'next'
import './globals.css'
import OpenBagProvider from '@/providers/OpenBagProvider'
import LoginProvider from '@/providers/LoginProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <OpenBagProvider>
          <LoginProvider>
            {children}
          </LoginProvider>
        </OpenBagProvider>
      </body>
    </html>
  )
}
