import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/layouts/header/Header'
import Footer from '@/components/layouts/Footer'
import OpenBagProvider from '@/providers/OpenBagProvider'
import { ClerkProvider } from '@clerk/nextjs'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ClerkProvider
        publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY as string}
        appearance={{
          layout: { 
            socialButtonsVariant: 'iconButton',
            logoImageUrl: '/assets/images/logo_mini.png'
          },
        }}
      >
        <OpenBagProvider>
          <body>
            <Header/>
            <div className=' mt-[155px]'>{children}</div>
            <Footer/>
          </body>
        </OpenBagProvider>
      </ClerkProvider>
    </html>
  )
}
