import type { Metadata } from 'next'
import './globals.css'
import OpenBagProvider from '@/providers/OpenBagProvider'
import LoginProvider from '@/providers/LoginProvider'
import LoginPopUp from '@/components/login/LoginPopUp'

export const metadata: Metadata = {
  title: 'wheneveratelier',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        {children}
      </body>
    </html>
  )
}
